format = '''[╭─](bold #50fa7b) $battery$container$all[╰─](bold #50fa7b)$username$hostname $character'''

[aws]
style = "bold #ffb86c"

[character]
error_symbol = "[❯](bold #ff5555)"
success_symbol = "[❯](bold #50fa7b)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
format = "@[$hostname]($style)"
style = "bold #bd93f9"

[username]
format = " [$user]($style)"
style_user = "bold #8be9fd"
